# Generated by Django 5.1.1 on 2025-05-02 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='intelreport',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='intelreport',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
